version: '2'
services:
  prod-nginx:
    build:
      context: ./.docker/prod/nginx
    container_name: prod-nginx
    networks:
      test_net:
        ipv4_address: 172.21.0.5
    links:
      - prod-node
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/dist:/usr/share/nginx/html
  prod-webpack:
    build:
      context: ./.docker/prod/webpack
    container_name: prod-webpack
    networks:
      test_net:
        ipv4_address: 172.21.0.6
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    stdin_open: true
    tty: true
    environment:
      - port=3000
      - NODE_ENV=production
    command: bash -c "tail -f /dev/null"
  prod-node:
    build:
      context: ./.docker/prod/node
    container_name: prod-node
    networks:
      test_net:
        ipv4_address: 172.21.0.7
    environment:
      - NODE_ENV=production
      - PORT=8081
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    ports:
      - "8081:8081"
    command: "npm start"

networks:
  test_net:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
