version: '2'
services:
  dev-nginx:
    build:
      context: ./.docker/dev/nginx
    container_name: dev-nginx
    networks:
      test_net:
        ipv4_address: 172.21.0.4
    links:
      - dev-node
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/dist:/usr/share/nginx/html
  dev-webpack:
    build:
      context: ./.docker/dev/webpack
    container_name: dev-webpack
    networks:
      test_net:
        ipv4_address: 172.21.0.2
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    ports:
      - "8080:8080"
    command: "npm run serve"
  dev-node:
    build:
      context: ./.docker/dev/node
    container_name: dev-node
    networks:
      test_net:
        ipv4_address: 172.21.0.3
    environment:
      - NODE_ENV=test
      - PORT=8081
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    ports:
      - "8081:8081"
    command: "npm start"

networks:
  test_net:
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16
