version: '2'
services:
  dev-nginx:
    build:
      context: ./.docker/dev/nginx
    container_name: dev-nginx
    links:
      - dev-node
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./client/dist:/usr/share/nginx/html
  dev-webpack:
    build:
      context: ./.docker/dev/webpack
    container_name: dev-webpack
    volumes:
      - ./client:/app
      - ./client/node_modules:/app/node_modules
    ports:
      - "8080:8080"
    command: "npm run serve"
  dev-node:
    build:
      context: ./.docker/dev/node
    container_name: dev-node
    volumes:
      - ./server:/app
      - ./server/node_modules:/app/node_modules
    ports:
      - "3000:3000"
    command: "npm start"
